name: Release

on:
  push:
    branches:
      - master

jobs:
  update_release:
    runs-on: ubuntu-latest
    steps:
      - uses: WangXin008/ProductHelpDocumentation@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
